import type { Brand } from "@/lib/types/brand"

// Define your token here
const LOGO_DEV_TOKEN = "pk_b5C_ydQ-R_mLijujC0OvfA";

const createBrand = (id: string, name: string, domain: string): Brand => ({
  id,
  name,
  image: `https://img.logo.dev/${domain}?token=${LOGO_DEV_TOKEN}`
});

export const mockBrands: Brand[] = [
  createBrand("1", "Samsung", "samsung.com"),
  createBrand("2", "Apple", "apple.com"),
  createBrand("3", "Sony", "sony.com"),
  createBrand("4", "LG", "lg.com"),
  createBrand("5", "Dell", "dell.com"),
  createBrand("6", "Nike", "nike.com"),
  createBrand("7", "Adidas", "adidas.com"),
  createBrand("8", "Microsoft", "microsoft.com"),
  createBrand("9", "Google", "google.com"),
  createBrand("10", "Amazon", "amazon.com"),
  createBrand("11", "Coca-Cola", "cocacola.com"),
  createBrand("12", "Pepsi", "pepsi.com"),
  createBrand("13", "Toyota", "toyota.com"),
  createBrand("14", "Honda", "honda.com"),
  createBrand("15", "Ford", "ford.com"),
  createBrand("16", "Tesla", "tesla.com"),
  createBrand("17", "BMW", "bmw.com"),
  createBrand("18", "Mercedes-Benz", "mercedes-benz.com"),
  createBrand("19", "Audi", "audi.com"),
  createBrand("20", "Volkswagen", "vw.com"),
  createBrand("21", "Intel", "intel.com"),
  createBrand("22", "AMD", "amd.com"),
  createBrand("23", "Nvidia", "nvidia.com"),
  createBrand("24", "Asus", "asus.com"),
  createBrand("25", "HP", "hp.com"),
  createBrand("26", "Lenovo", "lenovo.com"),
  createBrand("27", "Logitech", "logitech.com"),
  createBrand("28", "Razer", "razer.com"),
  createBrand("29", "Adobe", "adobe.com"),
  createBrand("30", "Netflix", "netflix.com"),
  createBrand("31", "Spotify", "spotify.com"),
  createBrand("32", "Disney", "disney.com"),
  createBrand("33", "McDonald's", "mcdonalds.com"),
  createBrand("34", "Starbucks", "starbucks.com"),
  createBrand("35", "Nestlé", "nestle.com"),
  createBrand("36", "Unilever", "unilever.com"),
  createBrand("37", "P&G", "pg.com"),
  createBrand("38", "Visa", "visa.com"),
  createBrand("39", "Mastercard", "mastercard.com"),
  createBrand("40", "American Express", "americanexpress.com"),
  createBrand("41", "PayPal", "paypal.com"),
  createBrand("42", "Stripe", "stripe.com"),
  createBrand("43", "Airbnb", "airbnb.com"),
  createBrand("44", "Uber", "uber.com"),
  createBrand("45", "Lyft", "lyft.com"),
  createBrand("46", "Slack", "slack.com"),
  createBrand("47", "Zoom", "zoom.us"),
  createBrand("48", "Salesforce", "salesforce.com"),
  createBrand("49", "Oracle", "oracle.com"),
  createBrand("50", "IBM", "ibm.com"),
  createBrand("51", "Cisco", "cisco.com"),
  createBrand("52", "Xiaomi", "mi.com"),
  createBrand("53", "Huawei", "huawei.com"),
  createBrand("54", "Oppo", "oppo.com"),
  createBrand("55", "Vivo", "vivo.com"),
  createBrand("56", "Canon", "canon.com"),
  createBrand("57", "Nikon", "nikon.com"),
  createBrand("58", "Panasonic", "panasonic.com"),
  createBrand("59", "Philips", "philips.com"),
  createBrand("60", "Bose", "bose.com"),
  createBrand("61", "Sennheiser", "sennheiser.com"),
  createBrand("62", "Levi's", "levi.com"),
  createBrand("63", "Zara", "zara.com"),
  createBrand("64", "H&M", "hm.com"),
  createBrand("65", "Gucci", "gucci.com"),
  createBrand("66", "Prada", "prada.com"),
  createBrand("67", "Louis Vuitton", "louisvuitton.com"),
  createBrand("68", "Chanel", "chanel.com"),
  createBrand("69", "Hermès", "hermes.com"),
  createBrand("70", "Rolex", "rolex.com"),
  createBrand("71", "Seiko", "seiko.com"),
  createBrand("72", "Casio", "casio.com"),
  createBrand("73", "Gillette", "gillette.com"),
  createBrand("74", "Colgate", "colgate.com"),
  createBrand("75", "L'Oréal", "loreal.com"),
  createBrand("76", "Estée Lauder", "esteelauder.com"),
  createBrand("77", "Johnson & Johnson", "jnj.com"),
  createBrand("78", "Pfizer", "pfizer.com"),
  createBrand("79", "Moderna", "modernatx.com"),
  createBrand("80", "Boeing", "boeing.com"),
  createBrand("81", "Airbus", "airbus.com"),
  createBrand("82", "FedEx", "fedex.com"),
  createBrand("83", "UPS", "ups.com"),
  createBrand("84", "DHL", "dhl.com"),
  createBrand("85", "Shell", "shell.com"),
  createBrand("86", "ExxonMobil", "exxonmobil.com"),
  createBrand("87", "BP", "bp.com"),
  createBrand("88", "Chevron", "chevron.com"),
  createBrand("89", "Walmart", "walmart.com"),
  createBrand("90", "Target", "target.com"),
  createBrand("91", "Costco", "costco.com"),
  createBrand("92", "IKEA", "ikea.com"),
  createBrand("93", "Home Depot", "homedepot.com"),
  createBrand("94", "Lowe's", "lowes.com"),
  createBrand("95", "Nintendo", "nintendo.com"),
  createBrand("96", "Sega", "sega.com"),
  createBrand("97", "Electronic Arts", "ea.com"),
  createBrand("98", "Ubisoft", "ubisoft.com"),
  createBrand("99", "Roblox", "roblox.com"),
  createBrand("100", "Epic Games", "epicgames.com"),
];