import type { Brand, Category, Unit, Tax, Warehouse, Product } from "@/lib/types/product"

export const mockBrands: Brand[] = [
  { id: "1", title: "Samsung" },
  { id: "2", title: "Apple" },
  { id: "3", title: "Sony" },
  { id: "4", title: "LG" },
  { id: "5", title: "Dell" },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Electronics" },
  { id: "2", name: "Furniture" },
  { id: "3", name: "Clothing" },
  { id: "4", name: "Food & Beverages" },
  { id: "5", name: "Books" },
]

export const mockUnits: Unit[] = [
  { id: "1", unit_name: "Piece", base_unit: null },
  { id: "2", unit_name: "Box", base_unit: "1", operation_value: 12, operator: "multiply" },
  { id: "3", unit_name: "Carton", base_unit: "1", operation_value: 144, operator: "multiply" },
  { id: "4", unit_name: "Kg", base_unit: null },
  { id: "5", unit_name: "Liter", base_unit: null },
]

export const mockTaxes: Tax[] = [
  { id: "1", name: "VAT 15%", rate: 15 },
  { id: "2", name: "VAT 5%", rate: 5 },
  { id: "3", name: "GST 18%", rate: 18 },
]

export const mockWarehouses: Warehouse[] = [
  { id: "1", name: "Main Warehouse" },
  { id: "2", name: "Branch Warehouse 1" },
  { id: "3", name: "Branch Warehouse 2" },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    type: "standard",
    name: "Samsung Galaxy S23",
    code: "SGS23-001",
    barcode_symbology: "C128",
    brand_id: "1",
    brand_name: "Samsung",
    category_id: "1",
    category_name: "Electronics",
    unit_id: "1",
    unit_name: "Piece",
    cost: 650,
    profit_margin: 20,
    price: 780,
    wholesale_price: 720,
    alert_quantity: 10,
    tax_id: "1",
    tax_name: "VAT 15%",
    tax_method: "exclusive",
    warranty: 12,
    warranty_type: "months",
    product_details: "Latest Samsung flagship smartphone",
    qty: 45,
    images: ["/samsung-galaxy-s23.png"],
    is_variant: false,
    is_batch: false,
    is_imei: true,
    warehouse_stocks: [
      { warehouse_id: "1", warehouse_name: "Main Warehouse", quantity: 30 },
      { warehouse_id: "2", warehouse_name: "Branch Warehouse 1", quantity: 15 },
    ],
    featured: true,
    promotion: true,
    promotion_price: 699,
    is_active: true,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-15T14:30:00Z",
  },
  {
    id: "2",
    type: "standard",
    name: 'Apple MacBook Pro 14"',
    code: "AMBP14-002",
    barcode_symbology: "C128",
    brand_id: "2",
    brand_name: "Apple",
    category_id: "1",
    category_name: "Electronics",
    unit_id: "1",
    unit_name: "Piece",
    cost: 1800,
    profit_margin: 15,
    price: 2070,
    alert_quantity: 5,
    tax_id: "1",
    tax_name: "VAT 15%",
    tax_method: "inclusive",
    warranty: 24,
    warranty_type: "months",
    product_details: "M3 Pro chip, 16GB RAM, 512GB SSD",
    qty: 12,
    images: ["/silver-macbook-pro-desk.png"],
    is_variant: true,
    variants: [
      { id: "v1", name: "Space Gray", item_code: "AMBP14-002-SG", additional_price: 0 },
      { id: "v2", name: "Silver", item_code: "AMBP14-002-SL", additional_price: 0 },
    ],
    is_batch: false,
    is_imei: true,
    warehouse_stocks: [
      { warehouse_id: "1", warehouse_name: "Main Warehouse", quantity: 8 },
      { warehouse_id: "2", warehouse_name: "Branch Warehouse 1", quantity: 4 },
    ],
    featured: true,
    promotion: false,
    is_active: true,
    created_at: "2025-01-05T09:00:00Z",
    updated_at: "2025-01-10T11:00:00Z",
  },
  {
    id: "3",
    type: "combo",
    name: "Home Office Bundle",
    code: "HOB-003",
    barcode_symbology: "C128",
    category_id: "1",
    category_name: "Electronics",
    unit_id: "1",
    unit_name: "Piece",
    cost: 450,
    price: 549,
    tax_id: "2",
    tax_name: "VAT 5%",
    tax_method: "exclusive",
    product_details: "Complete home office setup bundle",
    qty: 20,
    images: ["/home-office-bundle.jpg"],
    is_variant: false,
    is_batch: false,
    is_imei: false,
    combo_products: [
      {
        product_id: "5",
        product_name: "Wireless Keyboard",
        product_code: "WKB-005",
        wastage_percent: 0,
        quantity: 1,
        unit_id: "1",
        unit_cost: 45,
        unit_price: 55,
        subtotal: 55,
      },
      {
        product_id: "6",
        product_name: "Wireless Mouse",
        product_code: "WMS-006",
        wastage_percent: 0,
        quantity: 1,
        unit_id: "1",
        unit_cost: 25,
        unit_price: 35,
        subtotal: 35,
      },
    ],
    warehouse_stocks: [{ warehouse_id: "1", warehouse_name: "Main Warehouse", quantity: 20 }],
    featured: false,
    promotion: false,
    is_active: true,
    created_at: "2025-01-08T13:00:00Z",
    updated_at: "2025-01-12T16:00:00Z",
  },
  {
    id: "4",
    type: "service",
    name: "Device Setup Service",
    code: "DSS-004",
    barcode_symbology: "C128",
    category_id: "1",
    category_name: "Electronics",
    unit_id: "1",
    unit_name: "Piece",
    cost: 20,
    price: 50,
    tax_id: "3",
    tax_name: "GST 18%",
    tax_method: "exclusive",
    product_details: "Professional device setup and configuration",
    qty: 1000,
    is_variant: false,
    is_batch: false,
    is_imei: false,
    featured: false,
    promotion: false,
    is_active: true,
    created_at: "2025-01-03T08:00:00Z",
    updated_at: "2025-01-03T08:00:00Z",
  },
  {
    id: "5",
    type: "digital",
    name: "Software License Pro",
    code: "SLP-005",
    barcode_symbology: "C128",
    file: "software-license-pro.zip",
    brand_id: "5",
    brand_name: "Dell",
    category_id: "1",
    category_name: "Electronics",
    unit_id: "1",
    unit_name: "Piece",
    cost: 80,
    price: 120,
    tax_id: "1",
    tax_name: "VAT 15%",
    tax_method: "inclusive",
    product_details: "Professional software license with 1-year support",
    qty: 500,
    is_variant: false,
    is_batch: false,
    is_imei: false,
    featured: false,
    promotion: true,
    promotion_price: 99,
    is_active: true,
    created_at: "2025-01-07T10:00:00Z",
    updated_at: "2025-01-14T12:00:00Z",
  },
]
